### ISSUE TITLE
Environment variables are not reserved when invoking win32 exe from WSL side

### ISSUE THREAD

**Issue by nu774** [rprichard/wslbridge#12]
When I run WSL bash.exe directly, then run cmd.exe from WSL shell, environment variables seem to be kept.
When I run cmd.exe from WSL shell launched via wslbridge, most of the environment variables usually seen in win32 are lost.

**Comment by rprichard** [comment]
It's working for me:

```
rprichard@duck15063 ~/proj/wslbridge
$ export A_FOO=BAR

rprichard@duck15063 ~/proj/wslbridge
$ cmd /c set | sort > A

rprichard@duck15063 ~/proj/wslbridge
$ ./out/wslbridge cmd.exe /c set | sort > B

rprichard@duck15063 ~/proj/wslbridge
$ diff -U3 A B
--- A   2017-05-15 15:21:42.687755600 -0700
+++ B   2017-05-15 15:22:05.274025600 -0700
@@ -1,4 +1,4 @@
-_=/cygdrive/c/Windows/system32/cmd
+_=./out/wslbridge
 A_FOO=BAR
 ALLUSERSPROFILE=C:\ProgramData
 APPDATA=C:\Users\rprichard\AppData\Roaming
```

**Comment by nu774** [comment]
Sorry, seems like I was using old binary compiled before https://github.com/rprichard/wslbridge/commit/d80c5d7011dffde747c6aad7270ec0661b5cb1bd . Now it works for me.
