### ISSUE TITLE
Check that the frontend and backend versions match

### ISSUE THREAD

**Issue by rprichard** [rprichard/wslbridge#24]
The frontend and backend have to be upgraded in lock-step. They are always packaged together, so this seems like a reasonable requirement. If someone upgrades only one of the binaries, though, the program can fail in subtle ways.

Version mismatch could become a hard error:
 - In the frontend, pass the version string on the backend command-line.
 - In the backend, if the version argument isn't the expected value, abort.

See https://github.com/rprichard/wslbridge/issues/18#issuecomment-350643153

**Comment by Biswa96** [comment]
This "version-checking-string" seems to be like the "key" exchange in the bash.exe command. What option should be added with that version argument? Like `wslbridge --version X.X`?
