### ISSUE TITLE
wslbridge error: failed to start backend process

### ISSUE THREAD

**Issue by lymansix** [rprichard/wslbridge#40]
wslbridge error: failed to start backend process note: backend error output: wslbridge-backend: wslbridge-backend.cc:45: int {anonymous}::connectSocket(int, const string&): Assertion `connectRet == 0' failed.

**Comment by lymansix** [comment]
`wslbridge error: failed to start backend process
 note: backend error output: wslbridge-backend: wslbridge-backend.cc:45: int {anonymous}::connectSocket(int, const string&): Assertion `connectRet == 0' failed.


ConEmuC: Root process was alive less than 10 sec, ExitCode=0.
Press Enter or Esc to close console...`

**Comment by lymansix** [comment]
I try to run bash.exe or wsl.exe, it's ok.
what's wrong with it?

**Comment by Biswa96** [comment]
cc @Maximus5

**Comment by BrianInglis** [comment]
https://conemu.github.io/en/BashOnWindows.html

**Comment by koppor** [comment]
Starts to happen with WSL2 and ConEmu. This page is on the first 10 google hits. - Solution posted at https://github.com/Maximus5/ConEmu/issues/2014#issuecomment-566097052 works:

Configure that start in the "{Bash::bash}" task as follows:

```cmd
set PATH="%ConEmuBaseDirShort%\wsl";%PATH% & wsl -d ubuntu
```

**Comment by da5atar** [comment]
Indeed, it solved my issue. Many Thanks!

**Comment by standin000** [comment]
> Starts to happen with WSL2 and ConEmu. This page is on the first 10 google hits. - Solution posted at [Maximus5/ConEmu#2014 (comment)](https://github.com/Maximus5/ConEmu/issues/2014#issuecomment-566097052) works:
> 
> Configure that start in the "{Bash::bash}" task as follows:
> 
> ```batchfile
> set PATH="%ConEmuBaseDirShort%\wsl";%PATH% & wsl -d ubuntu
> ```

only ubuntu doesn't work, Ubuntu with version works.

**Comment by DanSGiesbrecht** [comment]
This solved my issue as well, thanks!

**Comment by jelc53** [comment]
I'm sure this is user error, but when I run the fix suggested 
`set PATH="%ConEmuBaseDirShort%\wsl";%PATH% & wsl -d ubuntu
`
I get the following error
`bash: bg: %PATH%: no such job`

**Comment by koppor** [comment]
In my current Windows setup, I don't need to configure anything. Here the screensdhot of my config:

![grafik](https://user-images.githubusercontent.com/1366654/142977870-7eaeee4b-1e99-4737-94eb-2a202b687c58.png)

@jelc53 Replace the `%windir%...` string by `set PATH="%ConEmuBaseDirShort%\wsl";%PATH% & wsl -d ubuntu`.

**Comment by mankec** [comment]
This have worked for me since I am using Ubuntu 20.04. This is [cmder](https://cmder.net/), [which uses ConEmu as a terminal](https://conemu.github.io/en/cmder.html).

![image](https://user-images.githubusercontent.com/59803655/176947870-071ba4b4-2dd4-4d87-96d0-414e94a849bd.png)

**Comment by paulos-andrade** [comment]
> This have worked for me since I am using Ubuntu 20.04. This is [cmder](https://cmder.net/), [which uses ConEmu as a terminal](https://conemu.github.io/en/cmder.html).
> 
> ![image](https://user-images.githubusercontent.com/59803655/176947870-071ba4b4-2dd4-4d87-96d0-414e94a849bd.png)

Thank you!
