### ISSUE TITLE
pass on full environment

### ISSUE THREAD

**Issue by mintty** [rprichard/wslbridge#6]
Please export all environment variables towards WSL (by an option or better even by default).
See https://github.com/mintty/wsltty/issues/14#issuecomment-255712113

An empty parameter `-E` could trigger the current default behaviour (with the option of subsequent `-Evar` and `-Evar=val` options).

**Comment by mintty** [comment]
I see it's done already, just not released. So I'll refer to the "master" version in the wsltty update.

**Comment by mintty** [comment]
Ah, that's tricky... I used to download the binary release so I don't have to worry about the backend compilation. So I may need to download both and compile the frontend myself... Or can you make an update release please?

**Comment by rprichard** [comment]
Yeah, it's this commit: https://github.com/rprichard/wslbridge/commit/d80c5d7011dffde747c6aad7270ec0661b5cb1bd

I can get a new release (with binaries) posted to GitHub today.

**Comment by rprichard** [comment]
Ok, the fix is released is 0.2.1.

**Comment by mintty** [comment]
Thanks.
